package com.payconiq.assignment.Entity;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * @author User 
 * 		   Model Class for using stock mapped to stock table in h2 table
 *         with field stock id (Autogenerated) ,name(Stock name), amount of each
 *         stock, timestamp define the timestamp stock created/modified.
 */
@Entity
@EntityListeners({ AuditingEntityListener.class })
@Table(name = "stock")
@Audited
public class StockEntity {

	@Id
	@GeneratedValue
	private Long id;
	private String name;
	private Double amount;
	private Long timestamp;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public StockEntity() {
		super();
		// TODO Auto-generated constructor stub
	}

	public StockEntity(Long id, String name, Double amount, Long timestamp) {
		super();
		this.id = id;
		this.name = name;
		this.amount = amount;
		this.timestamp = timestamp;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Long getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Long timestamp) {
		this.timestamp = timestamp;
	}

	@PreUpdate
	public void onUpdate() {
		timestamp = new Date().getTime();
	}

	@PrePersist
	public void onCreate() {
		timestamp = new Date().getTime();
	}
}
